### ISSUE TITLE
Eternal Loop Kernel Reset at Jupyter 4.1 and SBCL 1.3.1

### ISSUE THREAD

**Issue by ryukinix** [fredokun/cl-jupyter#20]
```
CORRUPTION WARNING in SBCL pid 8320(tid 140737353799424):
Memory fault at (nil) (pc=0x10001b8d07, sp=0x7ffff2b27fb8)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
INFO: Control stack guard page unprotected
CORRUPTION WARNING in SBCL pid 8320(tid 140737353799424):
Enabling blocked gc signals to allow returning to Lisp without risking
gc deadlocks. Since GC signals are only blocked in signal handlers when 
they are not safe to interrupt at all, this is a pretty severe occurrence.

The integrity of this image is possibly compromised.
Continuing with fingers crossed.
fatal error encountered in SBCL pid 8320(tid 140737353799424):
maximum interrupt nesting depth (1024) exceeded
```

Always when I try eval some instrunction at any cell of jupyter I receive that message in kernel backend. After that the kernel is reloaded and restarted. Any ideas?

**Comment by fredokun** [comment]
Sorry for the delay, I've been busy with some other things...
This looks like an issue I've encountered while using SBCL with threads on a Mac.
If you are using MacOS then you may have a better cl-jupyter experience with CCL.
If you are using Windows I am sorry I don't have any license (I will make this clear in the readme).
In case the error you've encountered is on a linux box, then please could you tell me a little more the way you start cl-jupyter ... also what is your OS/distrib ? which version of SBCL are you using.

**Comment by ryukinix** [comment]
## Distro, compilers and jupyter info
I'm in a Linux, using a ArchLinux-based distro called [Manjaro](manjaro.github.io), version Capella number `15.2`. My version of SBCL is the same I pointed at title of issue: `1.3.1` and the jupyter kernel `4.1`.

I start the jupyter kernel normally with the `jupyter notebook` and creat later a notebook with the `SBCL Lisp` kernel.

## Some pictures

### starting
![screenshot_2016-05-03_05-52-15](https://cloud.githubusercontent.com/assets/7642878/14978712/380dac3a-10f4-11e6-9cb8-fb7ad60b2ccd.png)
### after a while, dead kernel
![screenshot_2016-05-03_05-53-03](https://cloud.githubusercontent.com/assets/7642878/14978714/3814c074-10f4-11e6-9077-5d9b8621e956.png)
### notification
![screenshot_2016-05-03_06-12-56](https://cloud.githubusercontent.com/assets/7642878/14979044/4da35340-10f6-11e6-9300-0982e1e7c918.png)
### so ask to restart and enter a loop
![screenshot_2016-05-03_05-52-39](https://cloud.githubusercontent.com/assets/7642878/14978713/380fee28-10f4-11e6-95fd-5f945ee8751b.png)

I try restart but is the same thing. A Eternal Loop of Eternal suffering & pain. T_T.

The `jupyter kernel` output log [is here](http://sprunge.us/SDHf).

**Comment by ryukinix** [comment]
```
[Hearbeat] starting...
[Kernel] Entering mainloop ...
[Shell] loop started
[Shell] loop started
[Heartbeat] thread started
Argh! corrupted error depth, halting
fatal error encountered in SBCL pid 31565(tid 140737353795328):
%PRIMITIVE HALT called; the party is over.
``` 

This is really funny.

**Comment by mobius-eng** [comment]
I second the error on Ubuntu 16.04  with SBCL 1.3.2

```
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 302, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexey/.local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/alexey/.local/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/home/alexey/.local/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/alexey/.local/lib/python3.5/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_console/app.py", line 110, in init_shell
    client=self.kernel_client,
  File "/home/alexey/.local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 251, in __init__
    self.init_kernel_info()
  File "/home/alexey/.local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 305, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```

**Comment by athena007** [comment]
@ryukinix 

You will need to update your quicklisp dist pkg.
If your are running sbcl then launch from terminal and run the following
1. (load "~/quicklisp/setup.lisp")
2. (ql:update-all-dists)

This is indeed related to issues with pzmq as discussed in the following link
http://stackoverflow.com/questions/34093656/jupyter-and-common-lisp
Update the pkgs resolves the incompatibility.

**Comment by nickmatheus** [comment]
I typed in the terminal from Ubuntu 16:
```
sbcl
(load "~/quicklisp/setup.lisp")
(ql:update-all-dists)
(quit)
jupyter notebook
```

And then I opened a SBCL Lisp notebook. Indeed, it continued to show the same mistake.

```
unhandled condition in --disable-debugger mode, quitting
[W 00:34:43.408 NotebookApp] KernelRestarter: restart failed
[W 00:34:43.409 NotebookApp] Kernel e711c39d-df78-4c3d-a138-12d6dd0e4fd9 died, removing from map.
kernel e711c39d-df78-4c3d-a138-12d6dd0e4fd9 restarted failed!
[W 00:34:43.437 NotebookApp] Kernel deleted before session
[W 00:34:43.438 NotebookApp] 410 DELETE /api/sessions/499d2bd8-1da5-488c-aa64-e5b8c3b0bcf7 (127.0.0.1) 2.92ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=lisp
^C[I 00:34:48.473 NotebookApp] interrupted
Serving notebooks from local directory: /media/matheus/4061d0a4-cf53-4621-8b69-c73f01b88eb0/home/matheus/Desktop/lista-2-nickmatheus
0 active kernels 
The Jupyter Notebook is running at: http://localhost:8888/?token=2950724cd72d1196a6f24e78d2269df713afc7b198be99ba
```

Does @fredokun or anyone know what to do?

**Comment by fredokun** [comment]
Did you first install cl-jupyter with `python3 ./install-cl-jupyter.py` ?
What is your version of SBCL ?  (mine is 1.3.14.debian)
